import { GetServerSideProps, GetServerSidePropsContext } from "next";
import Head from "next/head";
import React, { useEffect } from "react";
import Header from "../../components/Header/Header";
import Image from "next/image";
import FullDetailsCard from "../../components/Groups/FullDetailsCard";
import DisplayStoryCard from "../../components/StoryComponents/cards/DisplayStoryCard";
import Link from "next/link";

function Index({ data }: any) {
  useEffect(() => {
    console.log(data.stories);
  }, []);
  return (
    <div>
      <Head>
        <title>My Stories</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div>
          <div className="h-40 w-full border flex flex-col sm:flex-row items-center justify-center">
            <div className="max-w-lg w-full flex justify-start items-center">
              <div>
                <Image
                  className="rounded-full"
                  src={data.photo}
                  width="80px"
                  height="80px"
                  alt={data.username}
                />
              </div>
              <div>
                <h1 className="font-roboto text-2xl font-semibold text-gray-900 opacity-80">
                  {data.username}
                </h1>
              </div>
            </div>
          </div>
          <div>
            <div className="flex p-4 flex-wrap items-center justify-center gap-4">
              {data.stories.map((story: any) => {
                return (
                  <Link
                    key={story.storyId}
                    passHref
                    href={`/story/${story.storyId}`}
                  >
                    <div>
                      <DisplayStoryCard details={story} />
                    </div>
                  </Link>
                );
              })}
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

export default Index;

export const getServerSideProps: GetServerSideProps = async (
  context: GetServerSidePropsContext
) => {
  const { userId }: any = context.params;
  const res = await fetch(`${process.env.BASE_URL}/profile/${userId}`);
  const data = await res.json();
  console.log(data);
  if (res.status === 200) return { props: { data: data } };
  return { redirect: { destination: "/", permanent: true } };
};
