import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import Header from "../components/Header/Header";

const Home: NextPage = ({ stories }: any) => {
  useEffect(() => {}, []);
  return (
    <div>
      <Head>
        <title>My Stories</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="font-poppins">
        <Header />
        <div className=" box-border font-roboto">Hello World</div>
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async (context) => {
  const stories = await fetch("http://localhost:5000/story/all");
  const data = await stories.json();
  return {
    props: { stories: data },
  };
};
